# https://taskfile.dev

version: '3'

tasks:
  init:
    - terraform init

  build:
    dir: ../../nodejs
    cmds:
      - yarn compile

  plan:
    - terraform plan

  apply-yes:
    - terraform apply -auto-approve

  destroy-yes:
    - terraform destroy -auto-approve
