# https://taskfile.dev

version: '3'

tasks:

  install-brew:
    cmds:
      - brew tap cargo-lambda/cargo-lambda
      - brew install cargo-lambda

  install-cargo:
    cmds:
      - cargo install cargo-lambda

  install-pip3:
    cmds:
      - pip3 install cargo-lambda

  _install-darwin:
    cmds:
      - task: '{{if lt .OS_VERSION "11"}}install-cargo{{else}}install-brew{{end}}'
    vars:
      OS_VERSION:
        sh: sw_vers -productVersion

  _install-linux:
    cmds:
      - task: install-pip3

  install:
    desc: "install required packages"
    cmds:
      - task: _install-{{OS}}

  build:
    desc: "Build app binary"
    cmds:
      - cargo lambda build --release --arm64 --output-format zip

  test:
    cmds:
      - cargo test -- --nocapture

  ver1:
    cmds:
      - echo MacOS 10.x
    preconditions:
      - sh: "[[ $(sw_vers -productVersion) < 11 ]]"
        msg: "10.x"
  ver2:
    cmds:
      - echo MacOS 11.x
    preconditions:
      - sh: "[[ $(sw_vers -productVersion) >= 11 ]]"
        msg: "11.x"
